### ISSUE TITLE
multiline string should be left as is by indenter

### ISSUE THREAD

**Issue by tuncer** [rust-lang/rust-mode#102]
If you want to write a multiline string in a way that lets you edit it exactly as it's printed on the terminal, it's common to write something like this:

```
fn printsomething() {
    println!(
"line__1
line______2
line________3
line___________4"
        );
}
```

Unfortunately the indenter does not leave this as is but tries and indents it into something that makes it impossible to edit, unless you remember to not indent the string (or the region containing it).

**Comment by nikomatsakis** [comment]
More specifically, you mean that it indents the opening quote? I guess what you would like is to not indent the opening quote if it lies on column 1?

**Comment by tuncer** [comment]
That would be sufficient, yes.

**Comment by tuncer** [comment]
Ideally, rust.vim, rust-mode and rustfmt should converge on a common default style for this which supports untouched multiline strings.

**Comment by tuncer** [comment]
I haven't been able to build rustfmt from git for a couple months now, so I cannot test with a fresh rustfmt, but I wonder where we are with this issue.
