### ISSUE TITLE
broken indentation in large files over time

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-mode#104]
I'm sorry I can't give a more specific error report, but I find pretty consistently that editing the files in `librustc_mir`, such as:

    build/mod.rs
    tcx/expr.rs

results in broken indentation. The failures modes seem to be one of two things:

1. pressing tab moves the text way over somewhere to the right for no apparent reason
2. I get errors about mismatched parentheses

Annoyingly, when I copy and paste the text into a new buffer to try and narrow it down, the problems often go away -- even if I copy everything. Closing and re-opening the buffer also makes things work again, as does disabling angle-bracket matching. This seems to suggest some sort of state that is being corrupted. @MicahChalmer you may have a good guess as to what this state is.

**Comment by MicahChalmer** [comment]
Well shoot.  I tried playing with those files a bit and couldn't reproduce it, but I haven't had time to try very hard to do so.

My best guess, without having observed the bad behavior myself, is that it's not applying the syntax properties fully to identify non-angle-bracket `<` and `>` characters, which throws the parsing way off.  If you continually `backward-up-list` when in the broken state, do you eventually come to a `<` that should not be treated as an angle bracket?

**Comment by nikomatsakis** [comment]
@MicahChalmer I'll let you know next time it starts happening. I will also see if I can find a consistent set of actions to reproduce it...

**Comment by shepmaster** [comment]
I also saw this. I happen to have `global-auto-revert-mode` enabled, and I noticed it immediately after doing a `git checkout -p` in another window. This causes the buffer to change reasonably drastically.

**Comment by nikomatsakis** [comment]
On Tue, Dec 08, 2015 at 10:39:26AM -0800, Jake Goulding wrote:
> I also saw this. I happen to have `global-auto-revert-mode` enabled, and I noticed it immediately after doing a `git checkout -p` in another window. This causes the buffer to change reasonably drastically.

I also have that mode enabled, perhaps that is part of the trigger.

**Comment by MicahChalmer** [comment]
I don't know if it's the only trigger, but `auto-revert-mode` does give a reliable way to reproduce the bug.  Open a large enough file and jump to the end of it, with `auto-revert-mode` enabled.  Then have some other process change the file to add a non-angle-bracket `<` character somewhere before the start of where you're looking at it, but after the beginning.  (I'm not sure how far before the scroll position and after the beginning you have to be..)  It doesn't run the syntactic keywords searches to add the syntax properties and ends up treating the newly-added `<` as an angle bracket.  Scroll up to where the new character is and it will then add the property and the problem goes away.

That tells me it's what I thought: it isn't applying the syntax properties in all cases.
