### ISSUE TITLE
indentation fails for type arguments (`<>`) in some cases

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-mode#112]
Sometimes I find that indenting in a type argument list works, but often it does not. Here is a small example where it does not:

```rust
type SourceHashMap = FnvHashMap<InternedString, FnvHashSet<(Span, DepNode)>>;
type TargetHashMap = FnvHashMap<InternedString,
FnvHashSet<(Span, InternedString, ast::NodeId, DepNode)>>;
```

I would hope to see the following after indenting:

```rust
type SourceHashMap = FnvHashMap<InternedString, FnvHashSet<(Span, DepNode)>>;
type TargetHashMap = FnvHashMap<InternedString,
                                FnvHashSet<(Span, InternedString, ast::NodeId, DepNode)>>;
```

cc @MicahChalmer

**Comment by MicahChalmer** [comment]
When I try indenting your small example I get exactly what you were expecting to see.  Did you have angle bracket matching turned off?  Was it in the middle of a larger file, possibly another case of #104?

**Comment by nikomatsakis** [comment]
@MicahChalmer it was, though the behavior persisted even when I moved it to a smaller file -- but maybe I've configured angle bracket matching off, I sort of remember doing that (temporarily, I thought) in response to #104 at some point.

**Comment by nikomatsakis** [comment]
Given that I don't have anything reproducible just now, I'll close this, though I still observe this from time to time.
