### ISSUE TITLE
electric-indent mode does not match behavior of the C major mode

### ISSUE THREAD

**Issue by xeechou** [rust-lang/rust-mode#119]
when I enter the closing parenthesis in with rust-mode. I got un-aligned parenthesis like this

     fn main() {
          print("Hello world");
          }

After searching the google, I coundn't find the way to align the parenthesis in rust-mode.

**Comment by tomjakubowski** [comment]
If I copy that into a rust-mode buffer, mark the whole buffer and hit `<TAB>` to reindent it, it looks like this:

```rust
fn main() {
    print("Hello world");
}
```

Do you have [electric indent](https://www.gnu.org/software/emacs/manual/html_node/emacs/Indent-Convenience.html) enabled?  I do, and if I type your example out myself, the line indents at the correct level after I hit `<RET>`.

**Comment by kraai** [comment]
For what it's worth, the behavior differs from the behavior when editing a C file.  When I enter the following text into foo.c, the final `}` is moved to the first column as soon as it's entered, not once `<RET>` is pressed:
```c
int main(int argc, char **argv) {
  printf("Hello world");
  }
```

**Comment by nikomatsakis** [comment]
I updated the title to be more precise: it seems like the only issue here is that, in C mode, when hit `}` it automatically unindents, but in Rust mode one has to press enter? (I don't use electric indent mode, so I am not familiar with the behavior.)

**Comment by xeechou** [comment]
exactly, but I'm using auto-pair mode now, which saved me a lot trouble.

**Comment by tromey** [comment]
This works for me.  It requires that you have `electric-indent-mode` enabled (the default), and it also requires setting `electric-indent-chars`.  I do it this way:

```
(defun tromey-attach-rust-mode-hacks ()
  (setq-local electric-indent-chars (append '(?} ?\;)
					    electric-indent-chars)))

(add-hook 'rust-mode-hook #'tromey-attach-rust-mode-hacks)
```

With this, when I type the final `}`, the line is automatically reindented.

It's not clear to me that major modes should set this variable.  I guess I would think it was ok if someone surveyed existing "standard" modes to see what they do.

**Comment by Stebalien** [comment]
I fixed this in #136 (although I didn't handle `;`). python, perl-mode, js, ruby-mode, and css-mode all seem to modify this (and are distributed with emacs) so I'm guessing it's safe.

**Comment by MicahChalmer** [comment]
It does seem like most of the other major modes set it.  The modes based on `cc-mode` also do it (through a special binding rather than the `electric-indent-chars` variable) as well as the ones @Stebalien listed.  Based on that, I'd say it seems conventional to set it in `rust-mode`.

**Comment by tromey** [comment]
This can be closed now.

**Comment by MicahChalmer** [comment]
Closing because #136 was merged to fix it.
