### ISSUE TITLE
Highlighting problems

### ISSUE THREAD

**Issue by montag451** [rust-lang/rust-mode#124]
I have some highlighting problems with rust-mode. I installed the latest version from melpa (rust-mode-20160222.2142) on a vanilla Emacs (24.5.1). I opened a Rust file, the highlighting was correct as you can see on this screenshot:

![rust-mode_1](https://cloud.githubusercontent.com/assets/249317/13375584/fe6ef836-dda3-11e5-8715-15bc38ea1a80.png)

Then I closed Emacs, started it again and opened the same Rust file and for some unknown reasons some highlighting disappeared as you can see on this screenshot:

![rust-mode_2](https://cloud.githubusercontent.com/assets/249317/13375597/57935236-dda4-11e5-88ea-287ffcf44832.png)

If you need more information about this issue, let me know :)

**Comment by nikomatsakis** [comment]
For reference: the highlighting which disappeared was the `foo` and `main` names, right?

**Comment by montag451** [comment]
Yes :)
