### ISSUE TITLE
rustfmt causes indentation to get messed up

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-mode#127]
I haven't been able to narrow this down yet to a smaller buffer, but here is a consistent reproduction of a problem (for me at least). Start with [this input](https://gist.github.com/nikomatsakis/2ce0c51f1bcca16c1ec8) in some buffer. If you jump to the end and hit tab (M-x indent-for-tab-command) on the line `// need some logic for start state and eof`, then you should find that it stays put:

```
        ...
        // need some logic for start state and eof
    }
}
```

But if you then run `C-c C-f` (run rustfmt) and hit tab again, you will find that it jumps to the beginning of the line:

```
// need some logic for start state and eof
    }
}
```

If you close the buffer and re-open, things work fine again.

I encounter this quite regularly -- but my attempts to delete text out of the buffer often caused the issue to go away, so I'm leaving it as is.

cc @MicahChalmer this seems related to a previous issue we had with losing sync, iirc?

**Comment by MicahChalmer** [comment]
Yup, same underlying issue.  The fontification gets out of sync after the buffer contents are programmatically replaced completely, and you're scrolled down far enough past the beginning of the buffer.
