### ISSUE TITLE
Emacs: rust-indent-method-chains indents beginning of line oddly

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-mode#13]
<a href="https://github.com/ProjectMoon"><img src="https://avatars.githubusercontent.com/u/183856?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ProjectMoon](https://github.com/ProjectMoon)**
_Monday Jan 26, 2015 at 10:29 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/21650_

_This issue was labelled with: A-infrastructure in the Rust repository_

----

Trying out rust-mode in emacs, and set rust-indent-method-chains because I like me some aligned dots.

It does what it advertises, but for some reason shoves the beginning of the line (and thus the lines underneath it) over one more tab.

I'm using spaces for tabs, configured to width 4.

What I expect:

```rust
let x = thing.do_it()
             .aligned()
             .more_alignment();
```

What I get:

```rust
    let x = thing.do_it()
                 .aligned()
                 .more_alignment();
```

I am using el-get to install rust-mode so it should be pulling off the latest master.

**Comment by nikomatsakis** [comment]
Yes, I've observed this as well and it made me sad because the option is so beautiful when it works.

**Comment by nikomatsakis** [comment]
I'm having problems identifying just when this problem arises. It's not as simple as presented in the topic here. A standalone example would be helpful.

**Comment by nikomatsakis** [comment]
Ah, hmm, maybe it is. I just didn't have the option fully enabled.

**Comment by nikomatsakis** [comment]
I have a kind of working patch for this. It's sort of ad-hoc. I'm going to use it for a bit locally and submit it if it seems to be going ok.
