### ISSUE TITLE
How long should rust-mode keep supporting Emacs 23?

### ISSUE THREAD

**Issue by MicahChalmer** [rust-lang/rust-mode#137]
Is anyone using `rust-mode` regularly with emacs 23?  (The last version of emacs 23 was released in January 2012...three and a half years before Rust 1.0 was released, for what it's worth.)

I'm starting to see signs of slight hiccups for people trying to enhance rust-mode.  Nothing hard to overcome yet, but it could get more annoying later.

When is it time to cut it off?  When emacs 25 comes out?  When someone writes a feature that really needs something only available in emacs 24 and above?  Sooner than that?

**Comment by tromey** [comment]
This affects issue #139 as well.

**Comment by nikomatsakis** [comment]
Personally I think we should just drop emacs23 support now.
