### ISSUE TITLE
Inherit from prog-mode?

### ISSUE THREAD

**Issue by davidshepherd7** [rust-lang/rust-mode#139]
Is there a reason why `rust-mode` doesn't [derive from `prog-mode`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Major-Modes.html)? If not could you change it to do so?

I'm asking because it's caused a minor issue for someone trying to use [electric-operator](https://github.com/davidshepherd7/electric-operator/issues/32) with `rust-mode`, nothing that can't be worked around if necessary though.

**Comment by tromey** [comment]
It tries to derive from `prog-mode` if that is available, like:
```
(defalias 'rust-parent-mode
  (if (fboundp 'prog-mode) 'prog-mode 'fundamental-mode))

[...]

(define-derived-mode rust-mode rust-parent-mode "Rust"
[...]
```

But when I switch to a rust-mode buffer and evaluate `(derived-mode-p 'prog-mode)`, I get `nil`.  So, this isn't working as intended.
