### ISSUE TITLE
emacs auto-complete should be enabled by default

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-mode#14]
<a href="https://github.com/pcn"><img src="https://avatars.githubusercontent.com/u/1056756?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pcn](https://github.com/pcn)**
_Sunday Jan 04, 2015 at 06:33 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/20509_

_This issue was labelled with: A-infrastructure in the Rust repository_

---

Even without specialized support for e.g. names in crates, enabling auto-complete in rust-mode should be on by default to some extent.  

I'm not a guru, but I think that there are two approaches.  
1. Either auto-complete can be active by default (where it will pop-up completions as you type) 
2. or, if that's not preferred, auto-complete functionality should be bound to some fairly common key ("Tab", or "M-/" are the most common choices from what I'm aware of) that enables completion when the cursor is in the middle of some typed text (e.g. http://cx4a.org/software/auto-complete/manual.html#Trigger_Key).

For more advanced completion stuff, is there a canonical set of places that could be searched for symbols to be completed?  I searched and found this: http://www.reddit.com/r/rust/comments/1xfjo7/ide_support/.  Is there a plan for this kind of support?

**Comment by nikomatsakis** [comment]
I would personally prefer not to override the default bindings for tab and `M-/`, though I wouldn't object to having this be either an "easy-to-configure" option or bound to some other key. In particular I find the default binding for `M-/` pretty dang useful and I suspect that any rust-mode-specific completions will take some time to approach that level of utility (if they ever do).

**Comment by MicahChalmer** [comment]
The right way at this point to get useful auto-completion of rust code in emacs is to install [Racer](https://github.com/phildawes/racer) and the emacs package that comes with it.  I don't think there's anything that this package should do on its own without that.  I do think it could be helpful to mention and link to Racer in this repo's README, in case anyone is looking for it.

**Comment by brotzeit** [comment]
We recently decided to keep rust-mode a lightweight package. If you want to have more features by default, you can try https://github.com/brotzeit/rustic
