### ISSUE TITLE
Better integration with HideShow

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust-mode#143]
[HideShow](https://www.emacswiki.org/emacs/HideShow) is an emacs extension that does code-folding - you shift-middle-click somewhere and it'll hide/show that block of code. It's is bundled with emacs these days and to enable it you just have to add `(add-hook 'rust-mode-hook 'hs-minor-mode)` to your `init.el`.

It automatically works with rust-mode somehow (I couldn't find either project mention each other) but not very well - e.g. if you clone murarth/rusti, open src/input.rs and shift-middle click just after the curly brace in `impl InputReader {` (near line 97) it will end up looking something like:

```
impl InputReader {...}
   }
   // rest of class
}
```

If you shift-middle-click on the dots again, this seems to "fix" the behaviour, and subsequent clicks do what's intuitively expected. (To unhide you need to click on `InputReader`.)

**Comment by brotzeit** [comment]
I think this was fixed(I closed an issue recently that was about hideshow), otherwise feel free to open a new issue.
