### ISSUE TITLE
bad format on a source file with mod

### ISSUE THREAD

**Issue by liuchong** [rust-lang/rust-mode#149]
please refer to the below link:
>https://github.com/rust-lang-nursery/rustfmt/issues/939

It loaded the mod into the formated file.

**Comment by liuchong** [comment]
anyone else have the same issue?

**Comment by MicahChalmer** [comment]
Submitted two alternative pull requests to rustfmt to address this.

If rust-lang-nursery/rustfmt#966 is merged, then upgrading to a version of rustfmt with that change incorporated will fix this issue without a change to rust-mode.

If rust-lang-nursery/rustfmt#967 is merged instead, a change in rust-mode will be needed to fix it (along with an updated rustfmt.)

**Comment by liuchong** [comment]
It works, thanks a lot! 😃
