### ISSUE TITLE
emacs mode wraps comments incorrectly

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-mode#15]
<a href="https://github.com/brson"><img src="https://avatars.githubusercontent.com/u/147214?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [brson](https://github.com/brson)**
_Thursday Jan 22, 2015 at 20:42 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/21524_

_This issue was labelled with: A-tools in the Rust repository_

----

This is a regression that has existed for a while. If I enter a long line of comments:

```
    // The reason for the current stability level. If deprecated, the reason for deprecation.
```

and press Alt-Q it does this:

```
    // The reason for the current stability level. If deprecated, the
    reason for deprecation.
```

which is invalid syntax.

**Comment by shepmaster** [comment]
I cannot reproduce this with rust-mode `20150215.1646`.

**Comment by MicahChalmer** [comment]
I also can't reproduce it with `20150215.1646`.

**Comment by nikomatsakis** [comment]
Same, with commit 249e3cef5d3dacfec1c1947637d009dafa0fad8d (I don't know where these fancy version numbers come from :)

**Comment by MicahChalmer** [comment]
The version numbers come from MELPA.  It assigns a version based on the date of the commit that it pulled.  `20150215.1646` I believe corresponds to commit 97f6445.

I went to look at what Marmalade does...and it looks like that relies on the author to upload the package, which hasn't been done for rust-mode in quite a while.  I'll put up another issue about that, since the README still talks about installing from Marmalade as well as MELPA.

As for this issue, if nobody can reproduce it, should it be closed?

**Comment by utkarshkukreti** [comment]
Possibly related: While I get correct wrapping with `fill-paragraph`, I get the same result as @brson with `fill-region`.

If I add this to a brand new `rust-mode` buffer:

```
// The reason for the current stability level. If deprecated, the reason for deprecation.
// The reason for the current stability level. If deprecated, the reason for deprecation.
// The reason for the current stability level. If deprecated, the reason for deprecation.
```

and I run `mark-whole-buffer` and `fill-region`, I get:

```
// The reason for the current stability level. If deprecated, the reason for
deprecation.  // The reason for the current stability level. If deprecated, the
reason for deprecation.  // The reason for the current stability level. If
deprecated, the reason for deprecation.
```

but when I run the same two commands in `c-mode`, I get:

```
// The reason for the current stability level. If deprecated, the reason for
// deprecation.  The reason for the current stability level. If deprecated, the
// reason for deprecation.  The reason for the current stability level. If
// deprecated, the reason for deprecation.
```
(which is correct and identical to `fill-paragraph` in `rust-mode`)

Should this be in a new issue? (and can you all reproduce it?)

**Comment by MicahChalmer** [comment]
Yes, I can reproduce the issue as @utkarshkukreti explained it.  `fill-paragraph` (as long as the mark isn't active) but `fill-region` does not work (even if only one line is selected.)

**Comment by brson** [comment]
I also have to create a region.
