### ISSUE TITLE
Please do not execute rustfmt if flycheck failed

### ISSUE THREAD

**Issue by douglarek** [rust-lang/rust-mode#150]
```
$ echo 'fn hoge () -> u32 { 1+1 ' | rustfmt

echo 'fn hoge () -> u32 { 1+1 ' | rustfmt
stdin:1:26: 1:26 error: this file contains an un-closed delimiter
stdin:1 fn hoge () -> u32 { 1+1
                                ^
stdin:1:19: 1:20 help: did you mean to close this delimiter?
stdin:1 fn hoge () -> u32 { 1+1
                          ^
fn hoge() -> u32 {
    1 + 1
}
```

`rustfmt 0.4.1` does not STOP if codes have syntax errors, these error messages will be written into *.rs files, we should check flycheck errors first , if check failed, please do NOT execute rustfmt!

**Comment by nikomatsakis** [comment]
cc @fbergroth

**Comment by fbergroth** [comment]
I'm not using rust these days, so I haven't ran into this. This sounds like a bug that should be reported to rustfmt though, as it shouldn't write any files if the source is given via stdin.

**Comment by douglarek** [comment]
The latest `rustfmt 0.5.0` has fixed it, so close this issue.
