### ISSUE TITLE
Syntax highlighting and indentation incorrect with lifetimes

### ISSUE THREAD

**Issue by Taneb** [rust-lang/rust-mode#158]
The code whose syntax I want highlighting is as follows:
```rust
enum Thunk<'a, T> {
    Unevaluated(&'a FnOnce()),
}
```

However, emacs, in Rust mode, highlights it according to the following image:

![Program with faulty syntax highlighting and indentation](http://i.imgur.com/3Oq5GhV.png)

**Comment by tomjakubowski** [comment]
Are you running an old version of the `rust-mode` package? I have version 20160505.2130 and can't reproduce this. To get the version number, you can run `M-x describe-package<RET>rust-mode<RET>`

![screen shot 2016-06-18 at 10 31 25 pm](https://cloud.githubusercontent.com/assets/667901/16175490/6984661c-35a4-11e6-9b30-ede0b3e15870.png)

**Comment by Taneb** [comment]
That says I'm using version 0.1.0, which I guess is an old version. Updating fixes this.

Thanks very much for your help :)
