### ISSUE TITLE
rustc-scroll-down-after-next-error loops infinitely

### ISSUE THREAD

**Issue by dabrahams** [rust-lang/rust-mode#164]
Please see https://github.com/rust-lang/rust-mode/commit/40c33fd71d87e10776d86f15f35c4fb2a2202879#commitcomment-18636755

In addition to fixing the regexp as shown there, maybe you should think about doing something to prevent searching backward forever!  A single call to `search-backward-regexp` would surely be more efficient than looping anyhow.

**Comment by nikomatsakis** [comment]
I think this is fixed in master, though I agree that a `search-backward-regexp` would probably be better. :)
