### ISSUE TITLE
Cannot save if rust-format-on-save and rustfmt fails

### ISSUE THREAD

**Issue by evmar** [rust-lang/rust-mode#166]
If you have

```
  (setq rust-format-on-save t)
```

and your code has a syntax error in it anywhere, you can no longer save your file.
Instead when you save you get a "rustfmt failed, see buffer for details" message.

And then in the rustfmt buffer it typically just includes the entire text of your buffer, it's not super helpful.

I think it'd be better to always save, and just warn you that rustfmt failed.

**Comment by nikomatsakis** [comment]
Makes sense to me!
