### ISSUE TITLE
Highlight questionmark

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/rust-mode#171]
The `?` sigil should be indicated in a very noticeable way. I see two ways to do this:
1. Highlight the sigil itself in a bright color.
2. Put something in the gutter. For example: `?`, `⤴`, `⇡`, or even an image for GUI mode.

IMO a combination of the two would be nice but (1) is obviously much easier.

**Comment by Aankhen** [comment]
With #219 you can customize the face to use a reversed background if you want it to stand out. Is an indicator in the gutter still useful?

**Comment by tromey** [comment]
I merged the PR and I think this is fixed now.
We can always reopen if the gutter idea is still desirable.
