### ISSUE TITLE
How can I invoke cargo build when I invoke compile in emacs ?

### ISSUE THREAD

**Issue by shivanth** [rust-lang/rust-mode#193]
When I invoke compile in rust-mode, emacs runs make command. Is there any configuration to be done to invoke cargo instead of make ?

**Comment by tromey** [comment]
All I do is `M-x compile`, then edit the command line to read `cargo build`.  In my .emacs I have

```
(setq savehist-additional-variables '(compile-command))
(savehist-mode 1)
```

which arranges to save the most recent compile command (the compile command history is automatically saved by savehist).

I haven't found a need for more than this.  Is there something additional that you need?

**Comment by RalfJung** [comment]
I now have emacs do `(setq compile-command "cargo build")` when entering Rust mode. Would it make sense to do something like that per default? `make -k` is pretty much never right for Rust.

**Comment by Aankhen** [comment]
I believe #216 should resolve this.

**Comment by tromey** [comment]
This issue is fixed, so I'm closing it.  But see #226.  I will comment there.
