### ISSUE TITLE
"default" as a keyword is not highlighted

### ISSUE THREAD

**Issue by sunchao** [rust-lang/rust-mode#196]
The keyword "default" is not highlighted at the moment.

**Comment by tromey** [comment]
I think this refers to https://github.com/rust-lang/rfcs/blob/master/text/1210-impl-specialization.md, which is still unstable.

**Comment by sunchao** [comment]
Do we have to wait until it become stable so that we can add this as keyword? I think there're plenty of people developing in unstable mode.

**Comment by tromey** [comment]
I looked at this some today.  I have something that works ok for `default fn`, `default impl`, and `default type`.  But, I don't know if it makes sense to mix `default` with other qualifiers (and I couldn't find a grammar in any of the RFC material).  My patch also updates `rust-re-item-def-imenu`, but again maybe not in the correct way.

**Comment by tromey** [comment]
This was fixed by #209, though in the end I only did `default fn`.  It's easy to add new things there as they're added to the language.
