### ISSUE TITLE
Rust-mode keeps disabling smartparents

### ISSUE THREAD

**Issue by mrkajetanp** [rust-lang/rust-mode#202]
I noticed that while I'm using rust-mode, smartparents just keeps getting disabled out of the blue and I need to turn it back on every once in a while.
I'm not sure what exactly is the cause of it but if I find out, I'll surely add it here.
Did it happen to anyone else?

I'm using spacemacs if it's in any way important.

**Comment by CajetanP** [comment]
I just noticed that it's somehow related to yasnippet since smartparents gets disabled when I expand a snippet and reenabled when I'm done with the expanded code. However, sometimes it fails to reenable it.

**Comment by brotzeit** [comment]
Pretty old issue and I've seen some rust-mode specific lines in smartparens, so I hope this was fixed. Otherwise feel free to open a new issue.
