### ISSUE TITLE
String interpolation different color than strings.

### ISSUE THREAD

**Issue by lorenzoi** [rust-lang/rust-mode#203]
String interpolation should be a different color than the rest of the strings. If this is already a feature, what would the syntax for custom themes be?

**Comment by nikomatsakis** [comment]
Are you referring to `format!` etc?

**Comment by lorenzoi** [comment]
no. like 

`println!("{}", x)`

the `{}` and what ever is inside it should be a different color

**Comment by tromey** [comment]
I think this is done.
