### ISSUE TITLE
rustfmt should not stop just because it can't meet line length

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-mode#205]
If you try to rustfmt this input with `C-c C-f`:

```rust
fn main() {
    let x:
    &'static str = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
}
```

nothing happens, but the `*rustfmt*` buffer contains this:

```
fn main() {
    let x: &'static str = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
}
Rustfmt failed at stdin:2: line exceeded maximum length (maximum: 100, found: 168) (sorry)
```

In my ideal world, the changes would take effect, but we'd open up a `*rustfmt*` buffer showing the failures (and this would be in `compile-mode`, so that you can hit `M-x next-error` to jump to each message, but that's #204).

**Comment by cjhowe** [comment]
I implemented this exactly like you said with that pull request, except without #204. Enjoy!

**Comment by cjhowe7** [comment]
This is resolved.

**Comment by tromey** [comment]
Thanks!
