### ISSUE TITLE
Incorect Indentation

### ISSUE THREAD

**Issue by tubo28** [rust-lang/rust-mode#212]
Rust-mode cannot format this code correctly. Rustfmt works well.

```rust
fn main() {
    let a = [[0u32, 0u32]; 1];
    let i = 0;
    let x = a[i][(1 << i)]; // bad
    }
```

**Comment by tromey** [comment]
`rust-is-lt-char-operator` mis-classifies the `<<` as being angle brackets rather than an operator.

**Comment by tromey** [comment]
It also fails if you shorten that to `<`.

I have a patch that works for this case but I'm not 100% sure it is correct.

**Comment by tromey** [comment]
You can give that a try if you want.

**Comment by Dushistov** [comment]
@tromey 

I am not issue starter, but this patch works for me. May be time to merge?

**Comment by tromey** [comment]
Thanks, I had already forgotten about this :)
