### ISSUE TITLE
rust mode breaks  (goto-address-at-point) when there is trailing ')'

### ISSUE THREAD

**Issue by amosbird** [rust-lang/rust-mode#214]
For example `(http://www.google.com)`  .  (goto-address-at-point) will grab `http://www.google.com)` as url.

**Comment by tromey** [comment]
I tried this in text mode and C mode and it also fails there.  So I suspect maybe it's an underlying problem, not specific to rust-mode.  However, is there a mode where it does work for you?  I've been testing it without visiting the URL using `(browse-url-url-at-point)`, which is what `goto-address-at-point` eventually calls.

**Comment by amosbird** [comment]
yeah, I found that too. the only mode that works for me is `text-mode`

**Comment by amosbird** [comment]
hmm, `()` is valid url characters.      https://en.wikipedia.org/wiki/Dunnet_(video_game)

It seems text-mode is broken :)
