### ISSUE TITLE
Wrong type argument: number-or-marker-p, "Abort trap: 6"

### ISSUE THREAD

**Issue by yamafaktory** [rust-lang/rust-mode#215]
Hi & thanks for this awesome mode!

Since I've updated to the latest `rustfmt` (v0.1.3), the automatic running of rust-format-buffer when saving a buffer is no more working. Directly executing `C-c C-f` leads to the following error:

```Wrong type argument: number-or-marker-p, "Abort trap: 6"```

On the other hand, running `cargo fmt` is formatting the code correctly. I tried a `package-refresh-contents`, also removing the `elpa` directory to get everything fresh but the issue persists.

**Comment by yamafaktory** [comment]
Updating to rustfmt `v0.1.4` is still leading to same error.

**Comment by Menschenkindlein** [comment]
It looks like it is a problem with rustfmt itself: https://github.com/rust-lang-nursery/rustfmt/issues/1707

**Comment by Menschenkindlein** [comment]
In the linked issue there is a solution of the problem with env variables:
```sh
export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH
```
However, Emacs doesn't import all env variables by default.
I solved this problem with `exec-path-from-shell`:
```elisp
(require 'exec-path-from-shell)
(exec-path-from-shell-initialize)
;; This is used for rustfmt
(exec-path-from-shell-copy-env "LD_LIBRARY_PATH")
```

**Comment by yamafaktory** [comment]
@Menschenkindlein thanks for the tip! I'm already using `exec-path-from-shell` and tried to add the aforementioned last line without success. I also tried to export the env variable (somehow missing): `export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH`.

**Comment by Menschenkindlein** [comment]
@yamafaktory I didn't quite understand the sequence of your steps. For me it was this way:
1. I made `rustfmt` (not `cargo fmt`) work in shell by executing the `export` line
2. I added this export to `.profile` and checked whether it works for every new shell
3. I checked, whether the env variable is visible in Emacs with `(getenv "LD_LIBRARY_PATH")`
4. Then I added the `copy-env` line to `.emacs` and checked it again
What is the step you have troubles with?

**Comment by yamafaktory** [comment]
Ok, my bad... What I did was exactly the same except I just did a quick `export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH` in my current shell. Adding the export directly in my `.zshrc` fixed it, thanks a lot 👍. I'm closing the issue.
