### ISSUE TITLE
rust-beginning-of-defun can not find real function

### ISSUE THREAD

**Issue by Dushistov** [rust-lang/rust-mode#222]
As described in [comment](https://github.com/kwrooijen/cargo.el/issues/41#issuecomment-319317831) of kwrooijen/cargo.el#41 I have problem with `rust-beginning-of-defun`.

With rust code in literal string `rust-beginning-of-defun` works in wrong way:

```rust
fn test1() {
    let s = r#"
fn test2();
"#;<CURSOR_HERE>
}
```

`M-x rust-beginning-of-defun` jumps to `test2` not to `test1` as expected.

**Comment by tromey** [comment]
If you try this patch out, and it works for you, let me know and I will merge it.  Thanks.

**Comment by Dushistov** [comment]
@tromey 

Thanks, I tested this patch and it works for me.
