### ISSUE TITLE
Types using variable-font-lock-face in if-let bindings

### ISSUE THREAD

**Issue by jjwest** [rust-lang/rust-mode#232]
I noticed that after updating rust-mode types in if-let bindings now uses the variable font lock instead of the proper type font lock. Is this intended behavior? If so, for what reason? Cheers!

**Comment by tromey** [comment]
It's probably just a bug.  Can you post an example here?

**Comment by jjwest** [comment]
Here's a screenshot:

http://i.imgur.com/zWlfD3J.png

The first binding is highlighted correctly, but in the if-let statement the `Some` should match highlighting of the first one.
