### ISSUE TITLE
Find Implementation of traits

### ISSUE THREAD

**Issue by shivanth** [rust-lang/rust-mode#241]
I don't know if I'm asking too much from rsut-mode, but is there a way to search for all the implementation of a given trait in ... umm , maybe in current directory tree.. Looks like a task for grep, but still it would be nice to jump to all/some the impls of a trait from trait definition

**Comment by kraai** [comment]
It appears that the Rust Language Server already does this (see rust-lang-nursery/rls#181).  Instead of reimplementing it in rust-mode, would it be better to use the RLS instead?

**Comment by brotzeit** [comment]
We recently decided that rust-mode won't add lsp support, so you have to configure it yourself or try [rustic](https://github.com/brotzeit/rustic).
