### ISSUE TITLE
M-x compile should make more hyperlinks

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust-mode#247]
When I get an error message like this:

```
error[E0061]: this function takes 4 parameters but 3 parameters were supplied
   --> src/librustc_mir/transform/nll/mod.rs:43:41
    |
43  |       let free_regions = FreeRegions::new(infcx, source, param_env);
    |                                           ^^^^^^^^^^^^^^^^^^^^^^^^ expected 4 parameters
    |
   ::: src/librustc_mir/transform/nll/free_regions.rs
    |
133 | /     pub fn new(
134 | |         infcx: &InferCtxt<'_, '_, 'tcx>,
135 | |         raw_mir: &Mir<'tcx>,
136 | |         source: MirSource,
...   |
145 | |         }.init(infcx, source, param_env)
146 | |     }
    | |_____- defined here
```

Naturally i can jump to `nll/mod.rs:43:41`, but it'd be so great if I could jump to the definition from `free_regions.rs` too. (I think I'd prefer to have to actively select it, though, and to have M-x next-error skip over it.) There isn't a simple regex for this, I guess -- maybe it's time for us to have our own compilation mode? That's probably a crazy idea.

While I'm at it, the colors that M-x compile induces are kind of unfortunate. It'd be nice if we could get the full colors rustc uses.

**Comment by nikomatsakis** [comment]
Actually, we could relatively easily allow jumping to the file, then I can use M-x goto-line to jump to the line number.

**Comment by tromey** [comment]
I was thinking it would be great if the `Ennnn` text linked to the documentation.

**Comment by tromey** [comment]
>maybe it's time for us to have our own compilation mode? That's probably a crazy idea 

Actually I think it might be better.  The built-in compilation mode is kind of terrible :( and `next-error` and friends are already virtualized.  The main difficulty might be getting users to run the new command.

**Comment by tromey** [comment]
I've been going back and forth about this.

On the one hand, compilation mode is standard, despite its flaws; and it has lots of stuff in it, like menus and a bunch of key bindings and more.

On the other hand, wedging more complicated parsing into it looks like a pain.  A new mode could do anything it likes.

BTW there's already color-supporting code in Emacs, see `ansi-color.el`.  A new mode could use this easily.

**Comment by brotzeit** [comment]
I will give it a try.

**Comment by brotzeit** [comment]
I've been trying to get ansi-color to work, but I don't know how. I have found a docstring in helm that mentions 

> This is needed to provide compatibility for both emacs-25 and emacs-24.5
> as emacs-25 version of `ansi-color-apply' is partially broken."

Does anybody know if this was fixed in recent versions ? The only way I get ansi-colors is using `term` which doesn't use ansi-color.el...

**Comment by brotzeit** [comment]
The hyperlink was added with https://github.com/rust-lang/rust-mode/pull/265
I think colors will only work when we use a different process filter and this is only possible when we use our own process.

@mookid do you want rust-mode to start its own process instead of using the default compilation process ?

**Comment by mookid** [comment]
I think that can be closed now.
