### ISSUE TITLE
Looking for feedback

### ISSUE THREAD

**Issue by brotzeit** [rust-lang/rust-mode#255]
I've been trying to improve some [stuff](https://github.com/brotzeit/rust-mode-reloaded). Let me know what you think about it. I can rebase if you want to merge it.

Try these commands:
rust-compile
rust-recompile
rust-format-call
rust-run-clippy

**Comment by nikomatsakis** [comment]
Can you say a bit more about what has changed? i.e., how it works?

**Comment by tromey** [comment]
It looks like there are a bunch of rearrangements and code pulled into new files, mixed in with additions and other changes.  That's fine as an end result (depending on specifics) but it makes it much harder to examine the result and see what's really different.

**Comment by brotzeit** [comment]
I have added a derived mode with `define-compilation-mode` so we can make rust specific changes in a rust
compilation mode.

We don't get all escape sequences with the compilation process as it uses a dumb terminal. That's why I
introduced a custom process. I couldn't get ansi-color.el to work so I looked for an alternative.
The package `xterm-color` now translates the ansi color sequences into text properties. I've provided
a defcustom `rust-ansi-faces` and the default colors are taken from `term`.

There's a process for rustfmt, but its buffer also runs in the new compilation mode.

I basically added color support.

**Comment by Dushistov** [comment]
By the way:
> so we can make rust specific changes in a rust compilation mode

is it possible to merge some features from
https://github.com/kwrooijen/cargo.el
with new rust compilation mode?

**Comment by brotzeit** [comment]
The package also defines a derived mode. We could add the same features to this mode.

**Comment by sondr3** [comment]
Would it be possible to revisit this? It's fairly obvious that this package has more or less stalled, which is a shame, but @brotzeit has kept chugging along at his (now fork) for quite a while now. I think anyone who uses Emacs and Rust would benefit from a coordinated effort between this package and rustic. I'd love to help out but my elisp-fu is really weak.

**Comment by brotzeit** [comment]
I don't feel confident enough to maintain the official package and it seems we can't find somebody more experienced who reviews my changes. When more users try rustic and open bug reports, we will see if things work. But I don't want to push my changes to rust-mode without anybody taking a look at it.

**Comment by kurnevsky** [comment]
@brotzeit I didn't dig deep into source code of rustic but noticed that it contains a lot of copy-pasted code from `lsp-rust` and `flycheck`. Could you elaborate a bit why do you need it? Isn't it better to leave it to these packages?

**Comment by brotzeit** [comment]
While looking at the code of racer.el I realized that it contains a lot of code that isn't needed anymore because rls handles it now, so I removed it. I expected that I will also change the code of the lsp and flycheck packages, but I didn't so far.

Another reason for pulling these packages into rustic is that I think it's easier to improve things when most of the rust related code is in one package. It takes some time to find all packages and get them to work together. So I've tried to make it easier to get the basic features. You only have to install and require rustic and most stuff should work.

Most rust packages aren't actively maintained and maybe we can use rustic as a fresh start to provide better rust support.

**Comment by Dushistov** [comment]
>  I realized that it contains a lot of code that isn't needed anymore because rls handles it now, so I removed it

This is bad, because of I don't think that `rls` is ready to use, and will become ready to use in the near future. So I use only racer, because of I don't want wait rebuild of my workspace once more.

**Comment by brotzeit** [comment]
You can still use racer.el. Hopefully `rls` will be ready soon.

**Comment by Dushistov** [comment]
> You can still use racer.el with rustic

But I have `rls` installed via `rustup` to reports bugs time to time, I just do not use it.
Is any preference to disable automatic `rls` usage in `rustic`?

>  Hopefully rls will be ready soon.

According to authors: https://www.ncameron.org/blog/more-on-the-rls-and-a-1-0-release/
Something usable should be at "early 2020", but I am not sure that this true.
Because of `rustc` slow as hell now, so creation of IDE based on it looks strange,
not share results of work with `rustc` looks realy, realy strange.

**Comment by brotzeit** [comment]
@Dushistov `(setq rustic-rls-pkg nil)` should work now.
