### ISSUE TITLE
rust-enable-format-on-save + compile = annoying jump to end of buffer

### ISSUE THREAD

**Issue by Dushistov** [rust-lang/rust-mode#256]
This is bug is similar to #231, but instead of begin of buffer,
at now it jumps to the end of buffer with rust code.
I have applied fix from #251 

Steps to reproduce:

1. Split window by two and run compile command in the second one:
   `C-x 2` `C-x O` `M-x compile` choose and run compilation command
2. Return back to code window and choose code at the middle of buffer and change it's 
    formating in so way that `rustfmt` should modify it (Do not save buffer)
3. Jump to compilation window `C-x O` and press `g` 

as result the position of cursor in buffer with rust code will change to the end of buffer.

/cc @brotzeit

**Comment by brotzeit** [comment]
Can you do me a favor and try this with my [fork](https://github.com/brotzeit/rust-mode-reloaded). I have added a custom process and it's possible that this issue doesn't occur with it. If the problem still exists I will try to fix it.

**Comment by Dushistov** [comment]
@brotzeit 

I tried. For real project is does not work at all.

```
error[E0583]: file not found for module `cpp_code`
 --> /home/evgeniy/projects/rust-infra/swig/macroslib/src/cpp/mod.rs:1:5
  |
1 | mod cpp_code;
  |     ^^^^^^^^
  |
  = help: name the file either cpp_code.rs or cpp_code/mod.rs inside the directory "/tmp"
```

looks like it copy just one file into '/tmp' and run rustfmt for it?

But for dummy test project created with `cargo --new bin` it looks like work.

I wonder how scheme with copying will work for real projects, with tree of modules,
plus part of code is generated by `build.rs` and lay in `target` and included via `include!`?

**Comment by brotzeit** [comment]
Thanks for taking a look at it!
Actually you wouldn't even get this error with the current solution in rust-mode, because it is ignored when running rustfmt with stdin. I've tried it with a temp file as there are several issues with stdin, but I didn't think of this error.

What do you think would be the best solution. Switch to stdin again, try to ignore this error with the current solution or create a temp file in the project directory ?
I don't like the solution with the temp file, but I think stdin is currently not really usable.

**Comment by Dushistov** [comment]
@brotzeit 

>What do you think would be the best solution. Switch to stdin again, try to ignore this >error with the current solution or create a temp file in the project directory ?
>I don't like the solution with the temp file, but I think stdin is currently not really usable.

If I edit `foo.rs` why not just run `rustfmt` against `foo.rs` without stdin/temp etc?

`emacs` reload changed on disk file without problems and it saves position of cursor.
The only problem is time of reload, I think default timings like 5 seconds or so,
so may be force reload of current buffer after run of `rustfmt`.

**Comment by brotzeit** [comment]
I wouldn't have a problem with that. The best way would be reverting I guess, but I will check if this is practicable. 

But probably there will be complaints about it as it changes the user experience.

**Comment by Dushistov** [comment]
@brotzeit 

May be time  to ask emacs-devel for general infrastructure for that? `gofmt`/`clang-format-buffer` and so on all of them win from that too.

**Comment by brotzeit** [comment]
Maybe, but I don't think it would change anything for this issue. rustfmt just isn't ready.

And even if they would add something we could use it in 5 ? years.

**Comment by brotzeit** [comment]
It should work, but I just fixed it for now.

**Comment by Dushistov** [comment]
> Maybe, but I don't think it would change anything for this issue. rustfmt just isn't ready.
> And even if they would add something we could use it in 5 ? years.

Looks like function already exists in emacs 26: https://github.com/emacs-lsp/lsp-mode/pull/258#issuecomment-360667059 , also in lsp-mode#258 was implemented some work around for emacs 25.

**Comment by apiraino** [comment]
Hi,

not sure if relevant: I experience a slight variation of this issue: when I save the code is formatted and the cursor goes to the lower part of the buffer (as if running executing command `recenter-top-bottom` i.e. `C-l`).

Example:
https://asciinema.org/a/kDrKAA9n6OFkDKYEa4xSfYBbH

I'm using Emacs 25.2.2 on Linux and `rust-mode` 20180215.210

**Comment by apiraino** [comment]
Hi @zippy, I've opened a pull request #269 (no feedback so far) but _it works for me_ (© 2018). Could you try it and see if it works for you, too?

**Comment by brotzeit** [comment]
I added `save-excursion` to the function so it should work now(if it didn't already before).
