### ISSUE TITLE
Feature to lookup documentation at point

### ISSUE THREAD

**Issue by plumenator** [rust-lang/rust-mode#261]
Similar to Hoogle in `haskell-mode` perhaps?

**Comment by sebastiencs** [comment]
You can use [lsp-ui-doc](https://github.com/emacs-lsp/lsp-ui) (but it requires emacs 26) 
![lsp-hover](https://user-images.githubusercontent.com/5273820/35660071-40099846-070a-11e8-8c31-87a90d4c7849.gif)

There is also [emacs-racer](https://github.com/racer-rust/emacs-racer) which provide the function `racer-describe`

**Comment by plumenator** [comment]
Wow! Thanks a lot!
