### ISSUE TITLE
rust-format-on-save not respecting local rustfmt.toml

### ISSUE THREAD

**Issue by ralphtheninja** [rust-lang/rust-mode#268]
I have the following lines in my `~/.emacs`:

```lisp
;; load rust-mode
(add-to-list 'load-path "/home/lms/dotfiles/emacs/site-lisp/rust-mode")
(autoload 'rust-mode "rust-mode" nil t)
(add-to-list 'auto-mode-alist '("\\.rs\\'" . rust-mode))
(setq rust-always-locate-project-on-open t)
(setq rust-indent-offset 2)
(setq rust-format-on-save t)
```

I'm aware that most projects are using 4 spaces but I need to get 2 space indentation working for a particular project.

My local `rustfmt.toml` looks like:

```toml
max_width = 80
tab_spaces = 2
```

When saving a file in emacs the indentation is still 4 spaces. However, when I manually do `cargo fmt` on the command line, it formats the code as expected.

Any ideas?

**Comment by ninrod** [comment]
Cannot reproduce. I've placed a rustfmt.toml in the git project root and all works fine.

**Comment by ralphtheninja** [comment]
It wasn't related to the emacs lisp. Fixed now :)
