### ISSUE TITLE
`let ref` not highlighted

### ISSUE THREAD

**Issue by cyrus-and** [rust-lang/rust-mode#271]
As the title says, take this example:

```rust
fn main() {
    let highlighted = ();
    let ref not_highlighted = ();
}
```

<img width="285" alt="screen shot 2018-06-07 at 16 30 54" src="https://user-images.githubusercontent.com/1660263/41106403-420d8908-6a70-11e8-8b8f-10ca5672de8a.png">

I'm using the latest version from MELPA.

**Comment by tromey** [comment]
Looks like a buglet here:
```
     ;; Type-inferred binding
     (,(concat "\\_<\\(?:let\\|ref\\)\\s-+\\(?:mut\\s-+\\)?" (rust-re-grab rust-re-ident) "\\_>") 1 font-lock-variable-name-face)
```
since if you remove the `let` from the source, the identifier is highlighted.

**Comment by cyrus-and** [comment]
I didn't check your commit nor the regex but the same happens also with `let ref mut`.
