### ISSUE TITLE
Setting `default-directory` for compilation mode

### ISSUE THREAD

**Issue by robsmith11** [rust-lang/rust-mode#275]
When I open source files, emacs always automatically sets the current directory to `/path/to/crate/src`, so after I compile and type `M-g n` to jump to the first error, I am prompted to enter the appropriate directory, which I must change to `/path/to/crate`.

To avoid the prompt, I must change the current directory after opening every source file.  Is there any way to get rust-mode to do this automatically?

**Comment by Dushistov** [comment]
You can look at https://github.com/kwrooijen/cargo.el , it parses `cargo metadata` and runs set right root directory for `compilation-mode`
