### ISSUE TITLE
wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by maris-orbidans-otm** [rust-lang/rust-mode#276]
c-c c-c c-b

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  locate-file-internal(nil ("./") nil #f(compiled-function (f) #<bytecode 0x400a65fd>))
  locate-file(nil ("./") nil #f(compiled-function (f) #<bytecode 0x400a65fd>))
  cd(nil)
  compilation-start("/Users/maris/.cargo/bin/cargo build --manifest-path /Users/maris/Projects/problem4/Cargo.toml " cargo-process-mode #f(compiled-function (_) #<bytecode 0x413428b5>))
  cargo-process--start("Build" "build")
  cargo-process-build()
  funcall-interactively(cargo-process-build)
  call-interactively(cargo-process-build nil nil)
  command-execute(cargo-process-build)

$ cargo --version
cargo 0.18.0 (fe7b0cdcf 2017-04-24)
$ which cargo
/Users/maris/.cargo/bin/cargo

package version:
rust-mode          20180626.1512 installed
cargo                  20180521.408  installed

GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-28

**Comment by brotzeit** [comment]
Please reopen this issue if it's still a problem.
