### ISSUE TITLE
Executing cargo-process-run is different from cargo run -p xxx

### ISSUE THREAD

**Issue by mickvangelderen** [rust-lang/rust-mode#280]
First of all, I'm not sure if this is a problem with rust-mode, but it is my best guess. I will try to explain my situation as best as possible. 

I'm working on an OpenGL project that I have been able to execute from emacs using cargo-process-run up until now. The project is in a workspace. After updating spacemacs to develop and all packages, I suddenly started getting the following error when running cargo-process-run:

```
thread 'main' panicked at 'Failed to initialize any backend!
    Wayland status: NoCompositorListening
    X11 status: XOpenDisplayFailed
```

When I run `cargo run -p xxx` from the command line, the application runs as it has before. 

Do you know of anything that has changed recently in emacs, rust-mode or one of its dependencies that might have changed the environment in which the process is ran?

**Comment by tromey** [comment]
`cargo-process-run` isn't defined by rust-mode.  So I suspect the problem is elsewhere.  `C-h f cargo-process-run` should show you where it is defined.

**Comment by mickvangelderen** [comment]
My apologies. Thank you for taking the time to respond and teach me something about emacs!
