### ISSUE TITLE
`use` is not a defun

### ISSUE THREAD

**Issue by iitalics** [rust-lang/rust-mode#283]
`rust-top-item-beg-re` lists "use" as one of the keywords that marks the beginning of a definition. However use really is not a definition at all, it typically only makes up one line, and, crucially, "use" statements can be nested within functions. The presence of `use` in this list makes `mark-defun` very annoying to use when you have nested `use` statements. I would like to know if there is a specific use case for `use`-as-a-defun that I'm not seeing, otherwise I think it should be removed from the list.

**Comment by brotzeit** [comment]
You're right. Better late than never.
