### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by phillord** [rust-lang/rust-mode#286]
The last release was 2016 and there have been lots of commits since then.

Perhaps I am the only person in the world using melpa-stable.

**Comment by danmack** [comment]
I just updated from elpa and have v0.4.0 which appears to be the same as master now 👍 
$ diff rust-mode-20181008.1628/rust-mode.el rust-mode-github-master/rust-mode.el
4d3
< ;; Package-Version: 20181008.1628

**Comment by pnkfelix** [comment]
Based on what went on in issues #87 and #179 ... well, I'm trying to figure out what the right steps here are?

Is it just a matter of updating the version number in the .el file (as PR #178 did) and then tagging that commit as a release?

If so, I guess all I ask is that someone who *uses* melpa-stable to actually go ahead and make a commit with a version bump and submit a PR for that. And then I'll see about making a new tag for that release.

**Comment by pnkfelix** [comment]
(I was tempted to assign myself, but I think that would give the wrong impression as if I were actually going to be the one to do the steps above. Since I do not use melpa-stable myself, I'm going to let someone else actually be the one who asserts "yes I tested this version out locally and it works in my melpa-stable environment."

**Comment by pnkfelix** [comment]
Oh I see, someone already did the step of bumping the version number in #267

**Comment by pnkfelix** [comment]
Okay I took the follow-on step of actually tagging the commit that bumped the version number (with that bumped version number) and then making a release off of that tag.

I'm going to *assume* that this is all that was needed to satisfy melpa-stable, and thus closing this issue. Do let us know if there are any remaining issues.

**Comment by kraai** [comment]
Thank you.  I've packaged the new version for Debian.
