### ISSUE TITLE
Use `cargo fmt` instead of `rustfmt`

### ISSUE THREAD

**Issue by vmalloc** [rust-lang/rust-mode#289]
For Rust 2018, rustfmt does not work correctly (e.g. removes leading `::` from `use` statements. The fact that `rust-mode` runs it instead of `cargo fmt` makes it problematic for writing 2018 code...

It would be nice to have this mode use the recommended `cargo fmt` command instead of `rustfmt`.

Thanks in advance!

**Comment by vmalloc** [comment]
I stumbled upon it as a part of the Rust 2018 changes - where rustfmt did not respect the "Edition" directive in cargo.toml. I guess this is no longer the case so the priority of this should not be that critical IMO

**Comment by agrover** [comment]
Certainly still seems to be the case for me. See https://github.com/rust-lang/rustfmt/issues/3724

**Comment by topecongiro** [comment]
rustfmt does not respect Cargo.toml because it is intended for a stand-alone tool, even without cargo. You could still pass `--edition 2018` to rustfmt to let it understand that the files being passed use edition 2018.
