### ISSUE TITLE
Enable Travis CI on this repo

### ISSUE THREAD

**Issue by MicahChalmer** [rust-lang/rust-mode#3]
It'd be nice to get Travis running on this repo to check that PRs continue to pass the ERT unit tests.

**Comment by steveklabnik** [comment]
I'm not an emacs user, but I do have admin credentials. What are ERT unit tests?

**Comment by steveklabnik** [comment]
Oh, duh: https://github.com/rust-lang/rust-mode#tests-via-ert

**Comment by steveklabnik** [comment]
If you submit a PR to add the `.travis.yml`, I can make this happen.

**Comment by MicahChalmer** [comment]
PR submitted, see #16.  Though due to some issues it might need more review than one would initially think.

**Comment by nikomatsakis** [comment]
This is basically fixed it seems.
