### ISSUE TITLE
Some commands don't respect rust-cargo-bin

### ISSUE THREAD

**Issue by dfoxfranke** [rust-lang/rust-mode#311]
The `rust-compile`, `rust-test`, and `rust-run` commands just invoke cargo as `cargo` rather than using the customized value of `rust-cargo-bin`.

**Comment by dir-ableton** [comment]
I patched my rust-mode.el, all that is needed is a simple 

```
(defun rust-run ()
  "Run using `cargo run`"
  (interactive)
  (compile (concat rust-cargo-bin " run")))
```

etc.
