### ISSUE TITLE
rust-mode ignores my tab indentation settings

### ISSUE THREAD

**Issue by msrd0** [rust-lang/rust-mode#312]
I have `(setq-default indent-tabs-mode t)` in my `~/.emacs` file. This is being respected by all emacs modes appart from rust-mode. Now I do realize that it is recommended to use spaces in Rust, however I'd still like to use tabs. How can I make rust-mode respect my settings?

**Comment by thornjad** [comment]
Rust mode is explicitly overriding it: 

https://github.com/rust-lang/rust-mode/blob/c62185ae1c6edf0335261f169241eb8ee9713ad5/rust-mode.el#L1557

But it's easy enough to override with

```emacs-lisp
(add-hook 'rust-mode-hook 
          (lambda () (setq indent-tabs-mode t)))
```
