### ISSUE TITLE
rust-format-buffer does not work with 2018 edition

### ISSUE THREAD

**Issue by hdevalence** [rust-lang/rust-mode#320]
Running `rust-format-buffer` on 2018 code gives errors like `error[E0670]: `async fn` is not permitted in the 2015 edition`, even though the code's `Cargo.toml` specifies the 2018 edition.

**Comment by DouglasGray** [comment]
A quick fix for this seems to be adding a "rustfmt.toml" file in the same directory as your "Cargo.toml" file with the line:
`
edition = "2018"
`

**Comment by jiacai2050** [comment]
upstream issue: https://github.com/rust-lang/rust-mode/issues/320

**Comment by mookid** [comment]
Closing as upstream issue is fixed.
