### ISSUE TITLE
indenting creates tabs instead of spaces

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust-mode#330]
Since PR #324, indenting Rust code in emacs is creating tabs instead of spaces, which is not according to the usual Rust style. If this is intended, at least the documentation should suggest adding `(setq-local indent-tabs-mode nil)` as a hook.

**Comment by mookid** [comment]
Well, rust-mode should not prevent you from inserting tabs. You can do that if you want with `indent-tabs-mode`, but it is out of scope of a major mode.
