### ISSUE TITLE
End of string match failures

### ISSUE THREAD

**Issue by hugoduncan** [rust-lang/rust-mode#34]
Using `rust-mode.el` 8d99bf8, the following highlights everything after "xs" as a string literal.  Editting either string causes the syntax highlighting to work correctly (and reloading the buffer breaks it again).

```
fn g() -> &str {
    "Er"
}

fn g() -> bool {
    assert!(false,"xs");
    true
}
```

**Comment by MicahChalmer** [comment]
I'm pretty sure I know what's going on here, and that it was introduced by the raw string handling that just landed.  I'm looking into it.
