### ISSUE TITLE
Not to define "C-c d" keybinding

### ISSUE THREAD

**Issue by iquiw** [rust-lang/rust-mode#341]
According to [Key-Binding-Conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html#Key-Binding-Conventions)
> Don't define C-c letter as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users; they are the only sequences reserved for users, so do not block them. 

https://github.com/rust-lang/rust-mode/blob/1b3db883bccb0956e5f05b7312485b2b7a5fa70f/rust-mode.el#L1586

**Comment by mookid** [comment]
Agreed. This applies also for the other keybinding defined here.

**Comment by iquiw** [comment]
I think <kbd>C-c C-f</kbd> (which is the keybinding you referred to?) is OK.

According to Key-Binding-Conventions,
> Sequences consisting of C-c followed by a control character or a digit are reserved for major modes.

**Comment by mookid** [comment]
Thanks for the input. Fixed in 6a5725328a155e12fee567de03a4625e3eddac26

**Comment by iquiw** [comment]
@mookid Thanks!
