### ISSUE TITLE
Navigating with beginning-of-def/end-of-defun skips async functions

### ISSUE THREAD

**Issue by nicholasbishop** [rust-lang/rust-mode#345]
For example, with code like this:

```rust
fn foo() {}
async fn bar() {}
fn baz() {}
```
If I place the cursor at the end of the file and press `C-M-a` (`beginning-of-defun`) twice it will go to the third line and then skip directly to the first line.

Tested with rust-mode-20191123.1632.

**Comment by mookid** [comment]
fixed with #346. please test!

**Comment by nicholasbishop** [comment]
Confirmed working for me, thanks for the fix :)
