### ISSUE TITLE
rust-goto-format-problem: Search failed: "--> \\([^:]+\\):"

### ISSUE THREAD

**Issue by kaiwk** [rust-lang/rust-mode#360]
execute `rust-format-buffer`, it gives error

> rust-goto-format-problem: Search failed: "--> \\([^:]+\\):"

version: 20200303.932

**Comment by mookid** [comment]
Hi, when that happens, what is the content of the `*rustfmt*` buffer?

**Comment by zonotope** [comment]
I have a very similar problem, only a slightly different error message. When I execute `rust-format-buffer`, The error I get is:
> Search failed: "--> \\([^:]+\\):"

I think that error is close enough to warrant tacking onto this issue instead of opening another one, but please let me know if I should open another issue instead.

The contents of my `*rustfmt*` buffer after this error is:
> Unrecognized option: 'edition'

I'm using the 2018 edition of course, and I have that specified in my Cargo.toml:
```[package]
name = "powalert"
version = "0.1.0"
authors = ["ben lamothe <bl@732.one>"]
edition = "2018"

[dependencies]
battery = "0.7.5"
log = "0.4.8"
simplelog = "0.7.4"
```

**Comment by mookid** [comment]
@zonotope it's a bit weird, because it means that rustfmt fails to parse the --edition flag.

What does ` echo fn foo( | rustfmt --edition 2018` in syour shell respond?

Does #359 solve mitigate the issue?

**Comment by zonotope** [comment]
Ha!
```
% ➜ echo "fn foo(" | rustfmt --edition 2018            
Unrecognized option: 'edition'
```

I was running `rustfmt` with no arguments. Here's my `rustfmt` version:
```
% ➜ rustfmt --version                                  
rustfmt 0.99.5-nightly ( )
```

Perhaps it's out of date? It seems weird that it would be _that_ out of date though.

**Comment by mookid** [comment]
```
$ rustfmt -V
rustfmt 1.4.11-stable (18382352 2019-12-03)
```
:)  

That explains that. Because it might happen, we should try to detect it to put a meaningful hint to the user.

**Comment by zonotope** [comment]
That worked! It looks like my version of `rustfmt` was managed by cargo instead of rustup and not being updated properly. Once I cleared that up, `rust-format-buffer` works for me now. Thanks!

**Comment by mookid** [comment]
cool! thanks for the feedback.

CLosing this for now, but I expect teh issue to be back as there seem to be non-handled outputs from rustfmt.
