### ISSUE TITLE
Package removed from Melpa?

### ISSUE THREAD

**Issue by Sparsa** [rust-lang/rust-mode#390]
Hi, Just wanted to install this mode on my emacs, but unfortunately the package is not available in melpa.

**Comment by mookid** [comment]
Tested just right now, and I can see the package available. Anybody else able to reproduce?

**Comment by brotzeit** [comment]
https://melpa.org/#/rust-mode

@Sparsa did you run `package-refresh-contents` ? I would recommend to use straight.el instead of package.el.

**Comment by mookid** [comment]
Closing, please reopen if you still can't find the package.
