### ISSUE TITLE
injected code results in errors that emacs hates

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-mode#4]
<a href="https://github.com/brson"><img src="https://avatars.githubusercontent.com/u/147214?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [brson](https://github.com/brson)**
_Wednesday Sep 19, 2012 at 00:56 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/3530_

_This issue was labelled with: A-diagnostics, A-tools, I-wrong, P-low in the Rust repository_

----

For example:

```
<core-macros>:3:10: 3:61 note: in expansion of #error
```

Emacs wants to load `<core-macros>` and interrupts your workflow to prompt for it. Injected code should come from files on disk (like intrinsic.rs) and we should use the correct file path when inserting them into the AST, so that the error messages work.

Alternately, we can come up with another way to indicate injected code so that the diagnostic emitter can generate error messages that emacs doesn't complain about. This could be a better solution, since getting dumped into core_macros.rs may not be so useful.

**Comment by MicahChalmer** [comment]
I'm going to call this closed by #84.  With that in place, it stops thinking that the lines `<std macros>` lines are errors, and doesn't prompt for a file name when you call `next-error`.
