### ISSUE TITLE
{forward,backward}-word behavior is unexpected

### ISSUE THREAD

**Issue by roysc** [rust-lang/rust-mode#41]
Because `_` is treated as a "word" character, functions operating on words do not behave in the usual way - eg. instead of jumping over "var" in  `var_name`, `forward-word` jumps over the whole symbol (ie. does the same thing as `forward-symbol`).
I tried to address this before but did not fix it properly, I will have a PR soon that is a proper fix.

**Comment by MicahChalmer** [comment]
This seems to be the same issue as #11.  I would think either this one or #11 should be closed as a duplicate.

**Comment by nikomatsakis** [comment]
Closing as dup of #11
