### ISSUE TITLE
Inconsistent highlighting at the start of a file

### ISSUE THREAD

**Issue by ddolgov** [rust-lang/rust-mode#412]
I am using manually installed rust-mode.el (no optional libraries, except rust-utils.el)) and syntax highlighting is inconsistent at the beginning of the file (see picture). If I add/delete some lines, the colors might change (for example, highlighting starts to work on all lines except the first one). 

Am I doing something wrong? How can I fix this?

Ubuntu 18.04
Emacs 24.5.1
rust-mode.el 0.5.0

![image](https://user-images.githubusercontent.com/10959837/131228404-fe298050-664f-4a92-b9a5-f008340617cf.png)

**Comment by psibi** [comment]
Is this reproducible with tree sitter support: https://github.com/rust-lang/rust-mode?tab=readme-ov-file#tree-sitter ?

**Comment by psibi** [comment]
I'm closing this issue for now as I haven't been able to reproduce it recently using tree sitter and haven't heard back. Please feel free to reopen it if you encounter the issue again in the future.
