### ISSUE TITLE
Support `cargo clippy --fix` on save, similar to `rustfmt` 

### ISSUE THREAD

**Issue by dconnolly** [rust-lang/rust-mode#413]
`cargo clippy --fix` has been [stabilized](https://github.com/rust-lang/rust-clippy/pull/7405) as of Rust 1.55. It would be great if `rust-mode` had an option to run and apply these fixes on save in basically the exact same way as `rustfmt` is now via `rust-format-on-save`.

**Comment by brotzeit** [comment]
I added this feature for rustic and I think it's better to use a hook that runs before compilation instead of a before-save hook.
