### ISSUE TITLE
`rust-beginning-of-defun` fails

### ISSUE THREAD

**Issue by tko** [rust-lang/rust-mode#416]
```rust
#[test]
fn it_works() {
    use super::*;
    assert!(false);
}
```
when cursor is anywhere after the `use` `rust-beginning-of-defun` fails with `Search failed: "fn "`

**Comment by psibi** [comment]
Can you check if this works with tree sitter: https://github.com/rust-lang/rust-mode?tab=readme-ov-file#tree-sitter

From my testing, it seems to work for me there.

**Comment by psibi** [comment]
I'm closing this issue for now as I haven't been able to reproduce it recently using tree sitter and haven't heard back. Please feel free to reopen it if you encounter the issue again in the future.
