### ISSUE TITLE
Prevent opening *rustfmt* in a frame on save if parsing fails

### ISSUE THREAD

**Issue by scd31** [rust-lang/rust-mode#432]
If I have a file that cannot be parsed (for instance, it's missing a parenthesis or semicolon), when I save the file, Emacs opens a new frame with the `*rustfmt*` buffer. This is already pretty annoying, but when I fix the error it doesn't even close the frame! (It just points the frame at whatever existing buffer I was looking at, so now I have two frames that are looking at the same buffer).

Is there a way I can turn this off? I would like rustfmt to fail silently if it can't parse my file.

**Comment by brotzeit** [comment]
`rust-format-show-buffer` maybe ?

**Comment by scd31** [comment]
Thank you! That fixed it.
