### ISSUE TITLE
Stop auto indentation when pressing enter

### ISSUE THREAD

**Issue by dayinjing** [rust-lang/rust-mode#437]
when I press enter the line is auto indented. This conflicts with the project I am working on. Because it has different indentation rules. So I always have to go back to un indent the previous line. Can we make that feature configurable? I can't use this thing on the project i'm working on if I have to go back and fix every SINGLE line I edit.

**Comment by brotzeit** [comment]
Now that you mention it, I think I would also turn it off =)
