### ISSUE TITLE
Question: how to add `--tests` to cargo check

### ISSUE THREAD

**Issue by k-bx** [rust-lang/rust-mode#439]
Hi. I'm using `C-c C-d` to run `cargo check` in a buffer. I'd love to extend the command to also check tests. What's the best way to do that atm? Thank you!

**Comment by brotzeit** [comment]
Hey, I'm afraid rust-mode doesn't provide this as a feature. So you can either additionally use a package from this list https://github.com/rust-lang/rust-mode#other-recommended-packages or look for a way to add additional parameters before running `compile`(requires a little elisp knowledge). Sorry that I don't implement it, but I don't want to add similar code in two places(I'm maintaining a package of the list I mentioned).

However I would gladly merge this feature. This would ideally be located at rust-compile.el.

**Comment by k-bx** [comment]
Gotcha. Just for clarity: would you be willing to expose an option that extends extra args in `customize-group` menu as PR?

**Comment by k-bx** [comment]
I've never done that, so not fully sure how to do that in elisp, but in haskell-mode for example you can say `M-x customize-group haskell-compile` and you will see something like this where you can override the stack build command from standard to whatever you want, adding any arguments you want.

<img width="935" alt="Screenshot 2022-02-02 at 19 17 07" src="https://user-images.githubusercontent.com/107968/152203941-fa5b28da-5797-4822-8f4b-89152c8bcd66.png">

**Comment by brotzeit** [comment]
I think this is only meant for the user side. I never used customize.

I just checked the keybinding `C-c C-d` and I couldn't find it in rust-mode. Can you tell me which command you are actually using. You probably use `rust-check` ?

**Comment by k-bx** [comment]
Yes, it's `rust-check`, I bind it myself

**Comment by brotzeit** [comment]
I added an option https://github.com/rust-lang/rust-mode/commit/832980d96a3b7e985bc8bfb1dc2bd7e9599c6312, try to use `(setq rust-cargo-default-arguments "--tests")` in your config.

**Comment by k-bx** [comment]
@brotzeit it worked, customized via `customize-group` GUI. thank you!
