### ISSUE TITLE
Marmalade is still recommended in the README, but package there is old and outdated

### ISSUE THREAD

**Issue by MicahChalmer** [rust-lang/rust-mode#44]
The README recommends either Marmalade or MELPA to install rust-mode.  MELPA automatically keeps itself up to date with the master branch from this repo.  Marmalade does not--the owner has to keep updating it themselves as far as I can tell.  It has a very old version up there now.

I would recommend one of these options:
- Set up a bot that uploads the latest version to Marmalade based on the master branch here
- Remove the package from Marmalade, and change the README recommend MELPA only

Either of these would require action from a Mozilla person--it can't be done in just a PR on this repo.

**Comment by pnkfelix** [comment]
According to PR #62, the only remaining step here is to remove the package from Marmalade itself...

but I personally don't know if that is the right call; it would presumably "break" some clients, forcing them to migrate to a local checkout or MELPA. Is there harm in just letting that old code sit out there?

**Comment by tromey** [comment]
Marmalade isn't really maintained.  I wonder if you can even remove things from it.  Anyway I think it's fine to just leave it alone and let users migrate to better-maintained archives, like melpa stable.

**Comment by brotzeit** [comment]
Not relevant anymore.
