### ISSUE TITLE
Completion highlighting is kinda broken.

### ISSUE THREAD

**Issue by Adomas-beep-boop-maggots** [rust-lang/rust-mode#448]
I tested a few completion UI's and a 2 of them dont work as intended. When I'm doing completion, only first character gets highlighted, and not the rest.  
# For example when i type want to complete something in [corfu](https://github.com/minad/corfu):
![image](https://user-images.githubusercontent.com/62380543/175374743-e9d00683-81c0-4043-af9e-2c0888e3af5e.png)
# In built-in completion ui:
![image](https://user-images.githubusercontent.com/62380543/175375060-e6c5f683-f71c-4c17-ab90-093ca5dd9560.png)
# [Company](https://github.com/company-mode/company-mode). works, no problem (:

![image](https://user-images.githubusercontent.com/62380543/175374868-e7e45df9-8d90-4179-83ea-b7a62eabc9c8.png)

**Comment by brotzeit** [comment]
company just highlights what you typed. rust-mode highlighting works by using regular expressions. It can't predict that you intend to type a macro call. If you want different default highlighting you have to change the default face.
