### ISSUE TITLE
Replace racer by rust-analyser

### ISSUE THREAD

**Issue by roastercode** [rust-lang/rust-mode#453]
Hi!
In the discussion [Cannot install racer](https://users.rust-lang.org/t/cannot-install-racer/78201/8?u=codex) it have been explained that racer is something like deprecated.

**Comment by brotzeit** [comment]
You can use https://github.com/rust-lang/rust-mode#lsp. rust-mode doesn't provide racer functionality, but I wouldn't remove it even if it was used.

**Comment by aurelien-git** [comment]
In the readme at https://github.com/rust-lang/rust-mode#auto-completion it says to use race.

here it should be replace by rust-analyser link and how installed it.

**Comment by brotzeit** [comment]
There are actually still people using racer or even rls. Some users don't like lsp. I don't think there's anything bad about giving them the choice to use their preferred tools. But we can add a note that racer deprecated ?
