### ISSUE TITLE
How to stop making new rustfmt windows?

### ISSUE THREAD

**Issue by lacker** [rust-lang/rust-mode#469]
I have rust-mode configured to run `rustfmt` on save, which generally I like. However, every time there's an error, it splits an existing window so that it can show the `*rustfmt*` buffer, and then after fixing the errors, it closes the `*rustfmt*` buffer, but leaves the new window configuration. So as I work it just slowly changes around my window setup. Can I avoid this behavior somehow while still automatically running `rustfmt` on save?

**Comment by brotzeit** [comment]
Try `(setq rust-format-show-buffer nil)`.

**Comment by lacker** [comment]
Perfect, thanks.
