### ISSUE TITLE
Incorrect indentation with character literal '('

### ISSUE THREAD

**Issue by gsingh93** [rust-lang/rust-mode#47]
Using the character literal '(' causes incorrect indentation:
```
fn base(&mut self) -> ParseResult {
    if self.peek() == '(' {
        self.consume('(').unwrap(); // The '(' here seems to be the problem
                     let r = try!(self.regex());
                     self.consume(')').unwrap();
        Ok(r)
    } else {
        Ok(RegEx::Terminal(self.next()))
    }
    }
```
I suspect this problem will occur other character literals but I haven't tested anything else.

**Comment by MicahChalmer** [comment]
I couldn't reproduce this.  I tried the above code in emacs 23, 24 and master and got the following correct indentation:

```rust
fn base(&mut self) -> ParseResult {
    if self.peek() == '(' {
        self.consume('(').unwrap(); // The '(' here seems to be the problem
        let r = try!(self.regex());
        self.consume(')').unwrap();
        Ok(r)
    } else {
        Ok(RegEx::Terminal(self.next()))
    }
}
```

What version are you using, and do you have the latest rust-mode?  Any settings in your own emacs config that make the issue appear/disappear?

**Comment by gsingh93** [comment]
Ah, sorry. I hadn't updated in two months, this is fixed in the latest version.
