### ISSUE TITLE
A Redundant Window Is Created, After 'rustfmt'ed

### ISSUE THREAD

**Issue by imichael2e2** [rust-lang/rust-mode#475]
For example, here is an error-syntax source file: 
```rust
xxxfn main() {}
```

Open it with either `emacs` or `emacs-nox`, run `rust-format-buffer` for it, an additional buffer `*rustfmt*` shows the stderr:
```
==================================
xxxfn main() {}
============test.rs===============
error: ...
1 | xxxfn main() {}
  |       ^^^^ expected one of `!` or `::`
============*rustfmt*=============
```

After fixed it,  run `rust-format-buffer` would result in two Window, both of which are showing the same file, like this:
```
==================================
fn main() {}
============test.rs===============
fn main() {}
============test.rs===============
```

The second Window might be **redundant**, hence the below one might be more appropriate: 

```
==================================
fn main() {}



============test.rs===============
```

For any lines of code, if there are some errors coming from `rustfmt`, it is expected that we are receiving that information in a seperate auxiliary Buffer,  `rust-mode` perfectly implements such feature. In addition, it is also expected that, once the errors are fixed and the code being formatted, the Buffer used for printing the previous errors should be closed and so does the corresponding Window, so that that the additional temporary Window will not occupy screen space any more. 

But due to the experiment shown above, it seems like `rustfmt` hasn't implemented such feature. For other language formatting packages, this is implemented, for example for `go-mode` package: https://github.com/dominikh/go-mode.el/blob/master/go-mode.el#L1989

**Comment by brotzeit** [comment]
Thanks.
