### ISSUE TITLE
Emacs mode has issues with single quotes

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-mode#5]
<a href="https://github.com/haxney"><img src="https://avatars.githubusercontent.com/u/88132?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [haxney](https://github.com/haxney)**
_Thursday Oct 31, 2013 at 04:58 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/10190_

_This issue was labelled with: A-tools in the Rust repository_

----

The latest version of `rust-mode` for Emacs (20130928.1740) has issues with
single-quoted characters, especially when that character is a `"` (double
quote). The following program executes correctly in Rust 0.8, but is font-locked
improperly in Emacs:

```rust
fn main() {
    println!("{}", '"');
}
```

It treats the double quote as the beginning of a string which runs to the end of
the file. If the double quote character is escaped like so:

```rust
fn main() {
    println!("{}", '\"');
}
```

Then there is not a problem with an unterminated string, but the characters
inside the single quotes are not fontified at all.

Note: Both programs compile and execute successfully under Rust 0.8.

This is related to #8793

**Comment by shepmaster** [comment]
I cannot reproduce the first issue (double quote in a single-quoted string) on rust-mode `20150215.1646`. The second issue (escaped double quote is not font-locked) still exists.

**Comment by MicahChalmer** [comment]
It's interesting that rust even accepts `'\"'`.  It isn't necessary (`'"'` is perfectly valid--and is now highlighted correctly in emacs too) and other unnecessary escapes get an "unknown character escape" compiler error.  It looks like [the same function is used to parse escapes inside either string or character literals](https://github.com/rust-lang/rust/blob/91a5a1ab4ad054c8dccf49f6f409542f82683cfc/src/libsyntax/parse/lexer/mod.rs#L783-870), which means that both `"\'"` and `'\"'` are valid escapes, even though they're unnecessary.
