### ISSUE TITLE
How to open document for the symbol under the cursor?

### ISSUE THREAD

**Issue by yhslai** [rust-lang/rust-mode#504]
According to the [changelog][1], Rust-Analyzer has a command `openDocs`. It should open the documentation for the symbol under the cursor.

How could I call this from emacs?

  [1]: https://rust-analyzer.github.io/thisweek/2020/10/19/changelog-47.html

**Comment by psibi** [comment]
If you are using lsp-mode, you need to use the function `lsp-rust-analyzer-open-external-docs` for it.
