### ISSUE TITLE
Integrating `rust-mode` with Built-in Tree-sitter in Emacs 29

### ISSUE THREAD

**Issue by creese** [rust-lang/rust-mode#506]
I've recently encountered an issue with Emacs 29. While the newer version has incorporated Tree-sitter by default, it seems that `tree-sitter-hl-mode` wasn't included.

Can anyone guide me on how to make rust-mode compatible with the integrated Tree-sitter in Emacs 29? Any help would be greatly appreciated.

**Comment by psibi** [comment]
This PR implements it: https://github.com/rust-lang/rust-mode/pull/482 

If you can test drive it, that will be helpful feedback.

**Comment by psibi** [comment]
Closing this since this is available as part of rust-mode: https://github.com/rust-lang/rust-mode?tab=readme-ov-file#tree-sitter
