### ISSUE TITLE
compilation-error-regexp not matching panics

### ISSUE THREAD

**Issue by ntBre** [rust-lang/rust-mode#507]
I'm not totally sure this is an issue or caused by this package, per se, but I've been having issues with my compilation links to errors. As you can see in the screenshot below, the warnings are working fine, but the whole panic line is turned into a link, and, more importantly, clicking the link brings up `Find this error in (default thread 'atom_typer::tests::atomtyper' panicked at src/lib.rs` rather than taking me to the file. I thought this might have to do with the "cleaner panic messages" from [Rust 1.73](https://blog.rust-lang.org/2023/10/05/Rust-1.73.0.html), but I still had a stable 1.72.1 version installed, and it had the same problem. I don't remember exactly when this stopped working, but I've just been dealing with it for a while and finally decided to ask for help.

I managed to get the behavior I wanted on the error with

```elisp
(setf
 (alist-get 'rustc compilation-error-regexp-alist-alist)
 '("thread '[^']+' panicked at \\(\\(.*\\):\\([0-9]+\\):\\([0-9]+\\)\\)" 2 3 4 nil 1))
```

but that obviously ruins the matching for warnings and other kinds of errors. I would really appreciate any help with this!

I've also been trying to use `rust-ts-mode` a bit, but I don't see anything in there that should be clashing with this option. I'm happy to provide any additional information that might be needed.

![image](https://github.com/rust-lang/rust-mode/assets/36778786/17d635d7-e892-4ee6-b9b7-34d6bc6ce75f)

**Comment by luckysori** [comment]
Great snippet, @ntBre! I was looking for someone with the same problem as me and someone from `#emacs:matrix.org` led me here.

> I would really appreciate any help with this!

I think I made it work by registering a new entry instead of overriding `rustc`:

```elisp
(defvar rustc-panics-compilation-regexps
  (let
      ((re
        "thread '[^']+' panicked at \\(\\(.*\\):\\([0-9]+\\):\\([0-9]+\\)\\)"))
    (cons re '(2 3 4 nil 1))))
(add-to-list
 'compilation-error-regexp-alist-alist
 (cons 'rustc-panics rustc-panics-compilation-regexps))
(add-to-list 'compilation-error-regexp-alist 'rustc-panics)
```

Thank you for sharing your fix!

**Comment by ntBre** [comment]
Wow, great idea! I'll give this a try tomorrow!

**Comment by ntBre** [comment]
Thanks again, this works great! I see now that your version is like the other definitions in `rust-compile.el`. There doesn't seem to be much activity here, but I think this (or something similar) should probably be included in the package if you wanted to submit a PR.

**Comment by luckysori** [comment]
@ntBre I opened https://github.com/rust-lang/rust-mode/pull/510 and added you as a co-author (I hope that's okay).

**Comment by ntBre** [comment]
Awesome, thank you!
