### ISSUE TITLE
Issues running this mode

### ISSUE THREAD

**Issue by DaKnig** [rust-lang/rust-mode#514]
updated some packages, updated emacs, and now I have the folowing error:
`funcall-interactively: Symbol’s value as variable is void: rust-mode-syntax-table`
it's all fun and games but I dont get syntax highlighting at all now... idk what to do...

**Comment by psibi** [comment]
Can you check if this PR makes it work for you: https://github.com/rust-lang/rust-mode/pull/515 ?

**Comment by DaKnig** [comment]
I followed the [directives on README](https://github.com/rust-lang/rust-mode?tab=readme-ov-file#manual-installation) with master (after 515 was merged) and it somehow works, I guess it fixed it.

**Comment by psibi** [comment]
Thanks for the confirmation!
