### ISSUE TITLE
Cannot setup LSP formatting and treesitter together

### ISSUE THREAD

**Issue by lerouxrgd** [rust-lang/rust-mode#516]
Hello,

Here is my current config:

```elisp
(use-package rust-mode
  :hook (rust-mode . lsp-deferred)
  :init
  (setq rust-mode-treesitter-derive t)
  :config
  (setq rust-format-on-save t
        rust-after-save-method 'lsp-format-buffer))
```

Then in rust-mode (when editing a Rust file), the format on save is not happening.

Strangely, it says:
```
run-hooks: Symbol’s function definition is void: rust-after-save-method
```
I keep having the same message if I try too change what is in the `:init` and `:config` statements.

**Comment by ccqpein** [comment]
I have the same issue and I even don't config the `rust-format-on-save`. I found the `rust-after-save-hook` is `rust-after-save-method`. Looks like #515 move `rust-after-save-hook` to `rust-common.el`, and the `rust-after-save-method` actually in `[rust-rustfmt.el](https://github.com/rust-lang/rust-mode/blob/ade453f95e95a3fb6ae90204e51571008fd25d48/rust-rustfmt.el#L365)`. Does `rust-common.el` forgot import the `rust-format`?

**Comment by psibi** [comment]
> Does rust-common.el forgot import the rust-format?

You're right. Does this PR make it work: https://github.com/rust-lang/rust-mode/pull/517 ?

**Comment by ccqpein** [comment]
@psibi Unfortunately, it doesn't, I try add `rust-rustfmt` in `rust-common` and it fixed on my side. 

```diff
modified   rust-common.el
@@ -4,6 +4,8 @@
 ;; rust-common code for both prog-mode and tree-sitter one
 
 ;;; Code:
+(require 'rust-rustfmt)
+
 (defcustom rust-before-save-hook 'rust-before-save-method
   "Function for formatting before save."
   :type 'function

```

**Comment by psibi** [comment]
@ccqpein Cool, want to send a PR with your changes ?

**Comment by ccqpein** [comment]
I just gave the PR #519 . cc @lerouxrgd does the PR fix the issue on your side too?
