### ISSUE TITLE
Default key bindings and rust-format-on-save doesn't work with rust-ts-mode

### ISSUE THREAD

**Issue by C-Entropy** [rust-lang/rust-mode#542]
My configuration:
```
(use-package rust-mode
  :hook
  ((rust-mode rust-ts-mode)
   .
   (lambda ()
     (setq indent-tabs-mode nil)
     (prettify-symbols-mode)))
  :config
  (setq rust-format-on-save t)
  :init
  (setq rust-mode-treesitter-derive t))
```

Default key bindings and rust-format-on-save doesn't work with rust-ts-mode.

**Comment by psibi** [comment]
The hook you secificied doesn't seem to be right, can you remove the hook and try without it ?

**Comment by psibi** [comment]
I tested it locally and this works for me:

```
(use-package rust-mode
  :ensure t
  :defer t
  :init
  (setq rust-mode-treesitter-derive t)
  :config
  (setq rust-format-on-save t))
```

**Comment by C-Entropy** [comment]
> I tested it locally and this works for me:
> 
> ```
> (use-package rust-mode
>   :ensure t
>   :defer t
>   :init
>   (setq rust-mode-treesitter-derive t)
>   :config
>   (setq rust-format-on-save t))
> ```

This works, thanks!
