### ISSUE TITLE
rust compile command does not scroll to the end of compile output result

### ISSUE THREAD

**Issue by getong** [rust-lang/rust-mode#550]
What I use with cargo:
```
(use-package cargo
  :straight t
  :config
  (setq compilation-scroll-output t)
  )
```
How can I scroll the output result?

**Comment by psibi** [comment]
I don't use the cargo package, probably best to ask this in the cargo repository issue tracker ?

**Comment by getong** [comment]
Does rust package compile the same behaviour with cargo package does? Can it scroll to the bottom of the compile output result automatically?

**Comment by psibi** [comment]
I tried building using `rustic-cargo-build` (from https://github.com/emacs-rustic/rustic) and I can see that it was scrolling fine.
