### ISSUE TITLE
Please consider making a new melpa-stable release

### ISSUE THREAD

**Issue by laurynas-biveinis** [rust-lang/rust-mode#551]
The last melpa-stable release was made in 2022. The current tree includes useful changes, particularly the treesitter support. Maybe it's time to make a new melpa-stable release?

**Comment by psibi** [comment]
Released a new tag: https://github.com/rust-lang/rust-mode/releases/tag/1.0.6

I believe melpa stable should have a build ready by eod today.

**Comment by psibi** [comment]
I see that a new version has been built: https://stable.melpa.org/#/rust-mode

Closing the issue, thanks for reporting!
