### ISSUE TITLE
Use `compilation-mode` for `rustfmt` errors

### ISSUE THREAD

**Issue by roife** [rust-lang/rust-mode#555]
See https://github.com/rust-lang/rust-mode/issues/204, https://github.com/rust-lang/rust-mode/pull/395.

This is crucial for user experience, yet it seems to have been neglected for quite some time.

Why can't we reuse `rust-compile.el` for `rustfmt`? Are there differences between the diagnostics format from `rustfmt` and `rustc`?

**Comment by roife** [comment]
I’m glad to tackle this issue, but I’m unsure if my approach (reusing `rust-compile.el`) is correct. I would greatly appreciate it if maintainers could provide some guidance.

**Comment by psibi** [comment]
Sure, I think it would be good to have it. If you want to take inspiration, it's already available as part of rustic mode: https://github.com/emacs-rustic/rustic/blob/d765680373234a6c231acf20c76b07422afcfdf9/rustic-rustfmt.el#L222

Also, please add tests too. :-)
