### ISSUE TITLE
`rust-re-ident` doesn't exist

### ISSUE THREAD

**Issue by vendethiel** [rust-lang/rust-mode#60]
Hi,

Seems like [this line](https://github.com/rust-lang/rust-mode/blob/1be7a946ed1cce8a2e4c462af8003c628770fed4/rust-mode.el#L126) uses a non-existent `rust-re-ident`. Not sure what's it's supposed to be -- but it seems to be missing.

**Comment by MicahChalmer** [comment]
It exists, it was just defined later in the file than its use.  Commit 96f7f79 fixed it.

**Comment by vendethiel** [comment]
Ah. Then github's in-file search must be broken still (not really surprised). Thanks!
