### ISSUE TITLE
Documentation String Highlight

### ISSUE THREAD

**Issue by JP-Ellis** [rust-lang/rust-mode#61]
It would be nice if documentation strings were highlight a different colour to the usual comment strings.  Emacs' font-lock seems to support documentation strings through setting `font-lock-doc-face`.  

The vim analogue of rust-mode does this and highlights documentation in a very-visible colour (red in solarized dark), this makes reading the documentation really nice within the code.

**Comment by gaudecker** [comment]
This should probably be closed as the issue was fixed in #71?

**Comment by JP-Ellis** [comment]
Indeed, this is fixed by #71.
