### ISSUE TITLE
emacs rust-mode.el: "file:line-num" output does not work with "note:"

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-mode#7]
<a href="https://github.com/pnkfelix"><img src="https://avatars.githubusercontent.com/u/173127?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pnkfelix](https://github.com/pnkfelix)**
_Monday Dec 23, 2013 at 18:24 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/11128_

_This issue was labelled with: A-tools, I-papercut in the Rust repository_

----

The problem described in #6887 is afflicting rustc's "note:" output, probably because the regexp added in 521fb049be4642919d690a01ef8617a9508d3909 only has cases for "error:" and "warning:", not "note:".

**Comment by MicahChalmer** [comment]
This was fixed already when it was moved from rust-lang/rust#11128 (as noted in the comments there.)  Closing it here as well.
