### ISSUE TITLE
Consider running checkdoc on rust-mode.el in the test suite

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust-mode#70]
checkdoc does some simple sanity checks to be sure that everything is well-documented.

http://cedet.sourceforge.net/checkdoc.shtml

**Comment by brotzeit** [comment]
I doubt anybody is motivated to add it.

**Comment by mookid** [comment]
Let's keep that open for now, and gradually improve the state of the doc.

**Comment by brotzeit** [comment]
I'll close this now. checkdoc can be pretty annoying when adding changes. And we obviously already have issues with contributions.
