### ISSUE TITLE
emacs mode indentation is wrong when function return -> is on its own line

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-mode#8]
<a href="https://github.com/nikomatsakis"><img src="https://avatars.githubusercontent.com/u/155238?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nikomatsakis](https://github.com/nikomatsakis)**
_Wednesday Apr 16, 2014 at 19:39 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/13566_

_This issue was labelled with: A-tools in the Rust repository_

----

The following code indents as shown here, which is weird:

```
pub fn from_pointer_kind(base_mutbl: MutabilityCategory,
                         ptr: PointerKind)
                         -> MutabilityCategory {
                             match ptr {
                             }
                         }
```

I expect it to be:

```
pub fn from_pointer_kind(base_mutbl: MutabilityCategory,
                         ptr: PointerKind)
                         -> MutabilityCategory {
    match ptr {
    }
}
```

**Comment by GBGamer** [comment]
Okay, the problem is with `(rust-rewind-to-beginning-of-current-level-expr)`.
When run in the first case:

```rust
pub fn test(...
	       |...) -> Test {
           ^ Point is here
}
```

it moves to

```rust
pub fn test|(...
	       ^ Point is here now
	         ...) -> Test {
}
```

However, when run with the ->, goes from

```rust
pub fn test(...)
	       |-> Test {
           ^ Point is here
}
```

to

```rust
pub fn test(...)
           |-> Test {
           ^ Point is here
}
```

As you can see, the point doesn't actually move at all. I'm working on some fixes.

The reason for this is that there is a check for

```lisp
(while (> (rust-paren-level) current-level)
```

Which is obviously only true when you are within the parentheses of the argument list.

Agh, this was meant to be put on #8

**Comment by nikomatsakis** [comment]
:racehorse: If you fix this bug, you'll be my official rust-mode "Hero of the Day". :)

**Comment by GBGamer** [comment]
I have fixed this bug, but the pull request has not been accepted :/

**Comment by GBGamer** [comment]
Check out #52

**Comment by GBGamer** [comment]
Oh, right. Making sure you read this, @nikomatsakis  :P
