### ISSUE TITLE
Function movement commands don't work

### ISSUE THREAD

**Issue by Wilfred** [rust-lang/rust-mode#83]
C-M-a and C-M-e (`beginning-of-defun` and `end-of-defun`) should move point to the beginning/end of functions. These currently don't work in rust-mode.

I believe this is also why C-x n d (`narrow-to-defun`) doesn't work.

**Comment by mrBliss** [comment]
All three commands work fine for me. Are you sure you're using the latest version?

**Comment by Wilfred** [comment]
Updating to latest rust-mode has indeed fixed it!
