### ISSUE TITLE
possible to show error messages on their own line?

### ISSUE THREAD

**Issue by blaenk** [rust-lang/rust-mode#92]
Woops, submitted before I wrote the body.

So I'm wondering if there's a way, any way, even a hack on my end, to show the error message starting on its own new line. For some reason the error messages show the full absolute path to the file which makes the error message wrap around unnecessarily in most cases.

Is there a way to make the error message show up on its own line?

See [this question](https://emacs.stackexchange.com/questions/14819/show-error-message-on-its-own-line) for a picture and more information.

Alternatively/additionally, is there a way to modify the way the file path is presented? I'd like to apply a function like `abbreviate-file-name` to it so that it becomes relative and shortens it a bit.

**Comment by pnkfelix** [comment]
Heh, the `rustc` compiler did this itself on its own, so our compilation output got the feature for free.

Closing.
